FROM tomcat:10.1-jdk17-temurin
WORKDIR /app
RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.118/bin/apache-tomcat-9.0.118.tar.gz
RUN tar -xvf apache-tomcat-9.0.118.tar.gz
RUN mv /app/apache-tomcat-9.0.107/ tomcat