FROM tomcat:9.0.118-jdk8-corretto-al2
WORKDIR /app
#RUN wget https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.118/bin/apache-tomcat-9.0.118.tar.gz
#RUN tar -xvf apache-tomcat-9.0.118.tar.gz
#RUN mv apache-tomcat-9.0.118/ tomcat
WORKDIR /app/tomcat/bin
CMD ["catalina.sh", "run"]